### ISSUE TITLE
condor submission script

### ISSUE THREAD

**Issue by Ming-Yan** [cms-btv-pog/BTVNanoCommissioning#90]
need to add lines below  `condor/executor.sh`
```bash
if [ "${ARGS[isSyst]}" != "null" ]; then
    OPTS="$OPTS --isSyst ${ARGS[isSyst]}"
fi
```

also the `arrays_` output directory are missing in the `iterative` executor  when scale out with condor jobs

**Comment by uttiyasarkar** [comment]
Fixed during the PR, the lines are added [here](https://github.com/cms-btv-pog/BTVNanoCommissioning/blob/70f87f19b5b7aa10ed848fbaa5a0cdb31a1e4aff/condor/execute.sh#L65)
